# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-22 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0003_remove_neighborhood_occupant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
