# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 08:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0005_auto_20181122_2115'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Userprofile',
        ),
        migrations.AlterField(
            model_name='business',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
