# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-24 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0009_auto_20181123_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighborhood',
            old_name='count',
            new_name='occupants_count',
        ),
    ]
